

cuboSemantico = {
    'int': {
        'int' : {
            '+' : 'int',
            '-' : 'int',
            '*' : 'int',
            '/' : 'int',
            '>' : 'bool',
            '>=' : 'bool',
            '<' : 'bool',
            '<=' : 'bool',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'int', 
            '&&' : 'err',
            '||' : 'err'  
        },
        'float' : {
            '+' : 'float',
            '-' : 'float',
            '*' : 'float',
            '/' : 'float',
            '>' : 'bool',
            '>=' : 'bool',
            '<' : 'bool',
            '<=' : 'bool',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'int', 
            '&&' : 'err',
            '||' : 'err'
        },
        'bool' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'char' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        }
  
    },
    'float' : {
        'int' : {
            '+' : 'float',
            '-' : 'float',
            '*' : 'float',
            '/' : 'float',
            '>' : 'bool',
            '>=' : 'bool',
            '<' : 'bool',
            '<=' : 'bool',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'float', 
            '&&' : 'err',
            '||' : 'err'
        },
        'float' : {
            '+' : 'float',
            '-' : 'float',
            '*' : 'float',
            '/' : 'float',
            '>' : 'bool',
            '>=' : 'bool',
            '<' : 'bool',
            '<=' : 'bool',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'float', 
            '&&' : 'err',
            '||' : 'err'
        },
        'bool' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'char' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        }

    },
    'bool' :{
        'int' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'float' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'bool' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'bool', 
            '&&' : 'bool',
            '||' : 'bool'
        },
        'char' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        }
    },
    'char' : {
        'int' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'float' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'bool' : {
            '+' : 'err',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'err',
            '>=' : 'err',
            '<' : 'err',
            '<=' : 'err',
            '!=' : 'err',
            '==' : 'err',
            '=' : 'err', 
            '&&' : 'err',
            '||' : 'err'
        },
        'char' : {
            '+' : 'char',
            '-' : 'err',
            '*' : 'err',
            '/' : 'err',
            '>' : 'bool',
            '>=' : 'bool',
            '<' : 'bool',
            '<=' : 'bool',
            '!=' : 'bool',
            '==' : 'bool',
            '=' : 'char', 
            '&&' : 'err',
            '||' : 'err'
        }
    }
}

#print(cuboSemantico.get('int').get('float').get('/'))